### ISSUE TITLE
swipe down refresh animation on cards view

### ISSUE THREAD

**Issue by fabiansch** [stampitamp/mobile#9]
In the moment swiping down on cards view will update the cards view without indicating this.

Swiping down on cards view should generate a little refresh animation on the top of the page that will disappear when the page is getting updated.

If the page will not get updated after a timeout of 10 seconds the refresh animation should change to a error notification that the connection seems to be poor.
Clicking on a "x" the user should be able to dismiss the notification.
Swiping down again will also dismiss the error notification and start the process again.

example for swipe down refresh animation:

![example for swipe down refresh animation](http://i2.wp.com/www.fmxexpress.com/wp-content/uploads/2014/02/pullto.jpg)

example for swipe down refresh error (red part is relevant):

![example for swipe down refresh error](https://community.smartthings.com/uploads/default/optimized/3X/8/8/88456a636b4af433703f3f05e1816b6a055646c5_1_281x500.jpg)

**Comment by danieltorrer** [comment]
Solved in commit https://github.com/stampitamp/mobile/commit/b3ea6cae4bcaa2fcfb3d7269220e2a5ad422ffbe

**Comment by fabiansch** [comment]
@danieltorrer good job but following is still missing:

>If the page will not get updated after a timeout of 10 seconds the refresh animation should change to a error notification that the connection seems to be poor.
Clicking on a "x" the user should be able to dismiss the notification.
Swiping down again will also dismiss the error notification and start the process again.
